// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 프리셋 삭제 응답
 */
export type DeletePresetResponse = { success: boolean, message: string, };
