// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MomentumResultDto } from "./MomentumResultDto";

/**
 * 모멘텀 스크리닝 결과 응답
 */
export type MomentumResponse = { total: number, days: number, min_change_pct: string, results: Array<MomentumResultDto>, };
