// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 모멘텀 스크리닝 쿼리
 */
export type MomentumQuery = { 
/**
 * 시장 필터
 */
market: string | null, 
/**
 * 조회 기간 (일)
 */
days: number, 
/**
 * 최소 변동률 (%)
 */
min_change_pct: string, 
/**
 * 최소 거래량 배율
 */
min_volume_ratio: string | null, 
/**
 * 결과 제한
 */
limit: number, };
