// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 프리셋 스크리닝 쿼리
 */
export type PresetQuery = { 
/**
 * 시장 필터 (KR, US)
 */
market: string | null, 
/**
 * 결과 제한
 */
limit: number | null, };
