// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 프리셋 저장 응답
 */
export type SavePresetResponse = { success: boolean, preset: Record<string, unknown>, message: string, };
