// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GlobalScore 계산 응답
 */
export type CalculateResponse = { 
/**
 * 처리된 종목 수
 */
processed: number, 
/**
 * 계산 시작 시간
 */
started_at: string, 
/**
 * 계산 완료 시간
 */
completed_at: string, };
