// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 랭킹 조회 쿼리
 */
export type RankingQuery = { 
/**
 * 시장 필터 (KR, US 등)
 */
market: string | null, 
/**
 * 등급 필터 (BUY, WATCH 등)
 */
grade: string | null, 
/**
 * 최소 점수
 */
min_score: string | null, 
/**
 * 반환 개수 (기본 50, 최대 500)
 */
limit: bigint | null, 
/**
 * RouteState 필터 (ATTACK, ARMED, WATCH, REST)
 */
route_state: string | null, };
