// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 7Factor 일괄 조회 요청
 */
export type SevenFactorBatchRequest = { 
/**
 * 티커 목록
 */
tickers: Array<string>, 
/**
 * 시장 (기본: KR)
 */
market: string, };
