// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 일별 손익 조회 쿼리 파라미터.
 */
export type DailyPnLQuery = { 
/**
 * 시작 날짜 (YYYY-MM-DD)
 */
start_date: string | null, 
/**
 * 종료 날짜 (YYYY-MM-DD)
 */
end_date: string | null, };
