// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolPnLItem } from "./SymbolPnLItem";

/**
 * 종목별 손익 응답.
 */
export type SymbolPnLResponse = { symbols: Array<SymbolPnLItem>, total: number, };
