// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 복사 응답.
 */
export type CloneStrategyResponse = { 
/**
 * 성공 여부
 */
success: boolean, 
/**
 * 원본 전략 ID
 */
source_id: string, 
/**
 * 생성된 전략 ID
 */
new_id: string, 
/**
 * 새 전략 이름
 */
new_name: string, 
/**
 * 메시지
 */
message: string, };
