// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 생성 응답.
 */
export type CreateStrategyResponse = { 
/**
 * 성공 여부
 */
success: boolean, 
/**
 * 생성된 전략 ID
 */
strategy_id: string, 
/**
 * 전략 이름
 */
name: string, 
/**
 * 메시지
 */
message: string, };
