// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 시작/중지 응답.
 */
export type StrategyActionResponse = { 
/**
 * 성공 여부
 */
success: boolean, 
/**
 * 전략 ID
 */
strategy_id: string, 
/**
 * 수행된 액션
 */
action: string, 
/**
 * 메시지
 */
message: string, };
