// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 목록 항목.
 */
export type StrategyListItem = { 
/**
 * 전략 ID
 */
id: string, 
/**
 * 전략 타입 (예: "rsi", "grid_trading", "sma" 등)
 */
strategyType: string, 
/**
 * 전략 이름
 */
name: string, 
/**
 * 전략 상태 ("Running", "Stopped", "Error")
 */
status: string, 
/**
 * 시장 ("KR", "US", "CRYPTO")
 */
market: string, 
/**
 * 거래 심볼 목록
 */
symbols: Array<string>, 
/**
 * 타임프레임 (1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1M)
 */
timeframe: string, 
/**
 * 손익
 */
pnl: number, 
/**
 * 승률
 */
winRate: number, 
/**
 * 거래 횟수
 */
tradesCount: bigint, 
/**
 * 리스크 프로필 (conservative, default, aggressive, custom)
 */
riskProfile: string | null, 
/**
 * 할당 자본
 */
allocatedCapital: number | null, 
/**
 * 다중 타임프레임 여부
 */
isMultiTimeframe: boolean, 
/**
 * 다중 타임프레임 설정 (NULL이면 단일 TF 전략)
 */
multi_timeframe_config: Record<string, unknown> | null, };
