// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 리스크 설정 변경 요청.
 */
export type UpdateRiskSettingsRequest = { 
/**
 * 리스크 설정 (RiskConfig 형식)
 */
risk_config: Record<string, unknown> | null, 
/**
 * 할당 자본 (NULL이면 전체 계좌 잔고 사용)
 */
allocated_capital: number | null, 
/**
 * 리스크 프로필 (conservative, default, aggressive, custom)
 */
risk_profile: string | null, };
