// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 심볼 변경 요청.
 */
export type UpdateSymbolsRequest = { 
/**
 * 새로운 심볼 목록
 */
symbols: Array<string>, };
