// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 전략 설정 변경 요청.
 */
export type UpdateConfigRequest = { 
/**
 * 새로운 설정 (JSON)
 */
config: Record<string, unknown>, };
